---
AWSTemplateFormatVersion: 2010-09-09
Description: Configure AWS Chatbot for cross-region notification to Slack.
Parameters:
  SnsTopicName:
    Description: SNS Topic Name.
    Type: String
    Default: guardduty-finding-topic
  SlackWorkspaceId:
    Description: Slack Workspace ID.
    Type: String
    Default: XXXXXXXXX
  SlackChannelId:
    Description: Slack Channel ID.
    Type: String
    Default: amazonguardduty
Resources:
  ChatbotConfiguration:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties:
      ConfigurationName: !Sub ${SnsTopicName}-chatbot-config
      IamRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/aws-service-role/management.chatbot.amazonaws.com/AWSServiceRoleForAWSChatbot
      LoggingLevel: NONE
      SlackChannelId: !Ref SlackChannelId
      SlackWorkspaceId: !Ref SlackWorkspaceId
      SnsTopicArns:
        - !Sub arn:aws:sns:us-east-1:${AWS::AccountId}:${SnsTopicName}
        - !Sub arn:aws:sns:us-east-2:${AWS::AccountId}:${SnsTopicName}
        - !Sub arn:aws:sns:us-west-1:${AWS::AccountId}:${SnsTopicName}
        - !Sub arn:aws:sns:us-west-2:${AWS::AccountId}:${SnsTopicName}
        - !Sub arn:aws:sns:ap-south-1:${AWS::AccountId}:${SnsTopicName}
        - !Sub arn:aws:sns:ap-northeast-3:${AWS::AccountId}:${SnsTopicName}
        - !Sub arn:aws:sns:ap-northeast-2:${AWS::AccountId}:${SnsTopicName}
        - !Sub arn:aws:sns:ap-southeast-1:${AWS::AccountId}:${SnsTopicName}
        - !Sub arn:aws:sns:ap-southeast-2:${AWS::AccountId}:${SnsTopicName}
        - !Sub arn:aws:sns:ap-northeast-1:${AWS::AccountId}:${SnsTopicName}
        - !Sub arn:aws:sns:ca-central-1:${AWS::AccountId}:${SnsTopicName}
        - !Sub arn:aws:sns:eu-central-1:${AWS::AccountId}:${SnsTopicName}
        - !Sub arn:aws:sns:eu-west-1:${AWS::AccountId}:${SnsTopicName}
        - !Sub arn:aws:sns:eu-west-2:${AWS::AccountId}:${SnsTopicName}
        - !Sub arn:aws:sns:eu-west-3:${AWS::AccountId}:${SnsTopicName}
        - !Sub arn:aws:sns:eu-north-1:${AWS::AccountId}:${SnsTopicName}
        - !Sub arn:aws:sns:sa-east-1:${AWS::AccountId}:${SnsTopicName}
        # - !Sub arn:aws:sns:af-south-1:${AWS::AccountId}:${SnsTopicName}
        # - !Sub arn:aws:sns:ap-east-1:${AWS::AccountId}:${SnsTopicName}
        # - !Sub arn:aws:sns:eu-south-1:${AWS::AccountId}:${SnsTopicName}
        # - !Sub arn:aws:sns:me-south-1:${AWS::AccountId}:${SnsTopicName}
Outputs:
  ChatbotConfiguration:
    Value: !Ref ChatbotConfiguration
    Export:
      Name: !Sub ${AWS::StackName}-ChatbotConfiguration
