---
AWSTemplateFormatVersion: 2010-09-09
Description: Configure Amazon GuardDuty, Amazon EventBridge, and Amazon SNS.
Parameters:
  SnsTopicName:
    Description: SNS Topic Name.
    Type: String
    Default: guardduty-finding-topic
Resources:
  GuardDutyDetector:
    Type: AWS::GuardDuty::Detector
    Properties:
      Enable: true
  SnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Ref SnsTopicName
  SnsTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: sns:Publish
            Resource: '*'
      Topics:
        - !Ref SnsTopic
  EventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub ${SnsTopicName}-event-rule
      EventPattern:
        source:
          - aws.guardduty
        detail-type:
          - GuardDuty Finding
      Targets:
        - Arn: !Ref SnsTopic
          Id: guardduty-sns-topic
