---
AWSTemplateFormatVersion: 2010-09-09
Description: IAM roles for CloudFormation StackSets
Resources:
  CloudFormationStackSetAdministrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCloudFormationStackSetAdministrationRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: AssumeRole-AWSCloudFormationStackSetExecutionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sts:AssumeRole
                Resource:
                  - arn:*:iam::*:role/AWSCloudFormationStackSetExecutionRole
  CloudFormationStackSetExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AWSCloudFormationStackSetExecutionRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess
Outputs:
  CloudFormationStackSetAdministrationRoleArn:
    Value: !GetAtt CloudFormationStackSetAdministrationRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-CloudFormationStackSetAdministrationRoleArn
  CloudFormationStackSetExecutionRoleArn:
    Value: !GetAtt CloudFormationStackSetExecutionRole.Arn
    Export:
      Name: !Sub ${AWS::StackName}-CloudFormationStackSetExecutionRoleArn
